# Generated by Django 2.1.7 on 2019-03-24 08:06

from django.db import migrations, models
import postAds.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_body', models.CharField(max_length=250)),
                ('post_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=postAds.models.get_image_path, width_field='width_field')),
                ('post_category', models.CharField(max_length=50)),
                ('post_created_at', models.DateTimeField(auto_now_add=True)),
                ('post_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
